11. Create a static navigation bar - Together with some clean up
antonsvaren/DAT257-DIT257-MANDALORE pull request #12
Opened 2022-10-05 17:19 UTC by antonsvaren

I have created a navigation bar and merged the "probability" and "main" branch into this one, in order to avoid merge conflicts. I have also cleaned up some code that we didn't use. It is only the "Weather" buttom and the "Climate" buttom that is currently working, as we only use two fragments at the minute. But the functions are easily extendable.

2022-10-06 17:44 UTC, ItsPonks requested changes
Remove .gitignore changes to match new .gitignore in main.

2022-10-06 19:24 UTC, Hannapham1007 approved these changes

2022-10-07 15:11 UTC, eliascalzone approved these changes

2022-10-08 13:38 UTC, ItsPonks approved these changes

2022-10-09 18:41 UTC, merged